import fs from 'fs';
import path from 'path';

const questions = [
  {
    id: "est1-sample1-q01",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Foundational Algebra",
    chapter: "Linear Equations & Systems",
    lesson: "Single-Variable Linear Equations",
    difficulty: "easy",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 60,
    prompt: "If $2x - 2 = 3x$, what is the value of $x + 2$?",
    question: "If $2x - 2 = 3x$, what is the value of $x + 2$?",
    choices: [
      { id: "A", text: "-4", isCorrect: false, is_correct: false, rationale: "Incorrect. Solves for 2x or arithmetic mistake." },
      { id: "B", text: "-2", isCorrect: false, is_correct: false, rationale: "Incorrect. This is the value of x, not x + 2." },
      { id: "C", text: "0", isCorrect: true, is_correct: true, rationale: "Correct! $2x - 2 = 3x \\implies 3x - 2x = -2 \\implies x = -2$. Then $x + 2 = -2 + 2 = 0$." },
      { id: "D", text: "2", isCorrect: false, is_correct: false, rationale: "Incorrect. Result if x = 0." }
    ],
    explanation: "First, solve for $x$:\n$$2x - 2 = 3x$$\nSubtract $2x$ from both sides:\n$$-2 = x \\iff x = -2$$\nNow substitute $x = -2$ into $x + 2$:\n$$x + 2 = -2 + 2 = 0$$\nTherefore, the correct choice is C."
  },
  {
    id: "est1-sample1-q02",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Foundational Algebra",
    chapter: "Linear Equations & Systems",
    lesson: "Single-Variable Linear Equations",
    difficulty: "easy",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 60,
    prompt: "If $\\frac{x}{3} = 3$ and $2y = 8$, what is the value of $\\frac{x}{y}$?",
    question: "If $\\frac{x}{3} = 3$ and $2y = 8$, what is the value of $\\frac{x}{y}$?",
    choices: [
      { id: "A", text: "\\frac{4}{9}", isCorrect: false, is_correct: false, rationale: "Incorrect. This is y/x instead of x/y." },
      { id: "B", text: "\\frac{9}{4}", isCorrect: true, is_correct: true, rationale: "Correct! $\\frac{x}{3} = 3 \\implies x = 9$ and $2y = 8 \\implies y = 4$. Thus $\\frac{x}{y} = \\frac{9}{4}$." },
      { id: "C", text: "3", isCorrect: false, is_correct: false, rationale: "Incorrect." },
      { id: "D", text: "6", isCorrect: false, is_correct: false, rationale: "Incorrect." }
    ],
    explanation: "Solve for $x$:\n$$\\frac{x}{3} = 3 \\implies x = 3 \\times 3 = 9$$\nSolve for $y$:\n$$2y = 8 \\implies y = \\frac{8}{2} = 4$$\nTherefore:\n$$\\frac{x}{y} = \\frac{9}{4}$$\nCorrect choice is B."
  },
  {
    id: "est1-sample1-q03",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Foundational Algebra",
    chapter: "Linear Equations & Systems",
    lesson: "Single-Variable Linear Equations",
    difficulty: "medium",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 75,
    prompt: "Tala spent $120 on a shopping spree. She bought a pair of pants for $50 and three identical t-shirts. Which of the following equations represents the scenario above, where $t$ is the price of one t-shirt?",
    question: "Tala spent $120 on a shopping spree. She bought a pair of pants for $50 and three identical t-shirts. Which of the following equations represents the scenario above, where $t$ is the price of one t-shirt?",
    choices: [
      { id: "A", text: "3t - 50 = 120", isCorrect: false, is_correct: false, rationale: "Incorrect. Subtracting pants instead of adding." },
      { id: "B", text: "50t + 3 = 120", isCorrect: false, is_correct: false, rationale: "Incorrect. Multiplying pants price by t." },
      { id: "C", text: "t + 50 = 120", isCorrect: false, is_correct: false, rationale: "Incorrect. Accounts for only one t-shirt." },
      { id: "D", text: "3t + 50 = 120", isCorrect: true, is_correct: true, rationale: "Correct! The cost of 3 t-shirts is $3t$, plus $50 for pants equals the total $120." }
    ],
    explanation: "The total expenditure is $120.\nTala buys 1 pair of pants for $50 and 3 t-shirts at price $t$ each.\nThe total cost equation is:\n$$3t + 50 = 120$$\nHence, the correct choice is D."
  },
  {
    id: "est1-sample1-q04",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Foundational Algebra",
    chapter: "Linear Equations & Systems",
    lesson: "Interpreting Slope and Intercepts in Applied Models",
    difficulty: "easy",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 60,
    prompt: "Which of the following lines is perpendicular to the line with equation $y = 3x - 2$?",
    question: "Which of the following lines is perpendicular to the line with equation $y = 3x - 2$?",
    choices: [
      { id: "A", text: "y = 3x + 1", isCorrect: false, is_correct: false, rationale: "Incorrect. This line is parallel, having slope 3." },
      { id: "B", text: "y = -\\frac{1}{3}x + 2", isCorrect: true, is_correct: true, rationale: "Correct! Perpendicular lines have negative reciprocal slopes: $m_2 = -\\frac{1}{3}$." },
      { id: "C", text: "y = -3x - 2", isCorrect: false, is_correct: false, rationale: "Incorrect. Slope is -3, not -1/3." },
      { id: "D", text: "y = \\frac{1}{3}x + 5", isCorrect: false, is_correct: false, rationale: "Incorrect. Slope is +1/3, missing the negative sign." }
    ],
    explanation: "The given line has slope $m_1 = 3$.\nTwo perpendicular lines have slopes whose product is $-1$:\n$$m_1 \\times m_2 = -1 \\implies 3 \\times m_2 = -1 \\implies m_2 = -\\frac{1}{3}$$\nThe line $y = -\\frac{1}{3}x + 2$ has slope $-\\frac{1}{3}$, so it is perpendicular.\nCorrect choice is B."
  },
  {
    id: "est1-sample1-q05",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Foundational Algebra",
    chapter: "Linear Equations & Systems",
    lesson: "Linear Inequalities & Shaded Coordinate Regions",
    difficulty: "hard",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 90,
    prompt: "Given $y \\ge 3x - 1$ and $y \\le 3x + 1$, which of the following is true about this system?",
    question: "Given $y \\ge 3x - 1$ and $y \\le 3x + 1$, which of the following is true about this system?",
    choices: [
      { id: "A", text: "It has no solution.", isCorrect: false, is_correct: false, rationale: "Incorrect. The lines are parallel and the region between them contains infinitely many points." },
      { id: "B", text: "It has an infinite number of solutions.", isCorrect: true, is_correct: true, rationale: "Correct! The solution is the strip between the two parallel boundary lines $y = 3x - 1$ and $y = 3x + 1$." },
      { id: "C", text: "It has only one solution.", isCorrect: false, is_correct: false, rationale: "Incorrect. An inequality system defining an area has infinite points." },
      { id: "D", text: "It has only two solutions.", isCorrect: false, is_correct: false, rationale: "Incorrect." }
    ],
    explanation: "The boundary lines are $y = 3x - 1$ and $y = 3x + 1$.\nBoth lines have the same slope $m = 3$ and are therefore parallel.\nThe inequality $y \\ge 3x - 1$ represents the region on and above the lower line.\nThe inequality $y \\le 3x + 1$ represents the region on and below the upper line.\nThe intersection is the continuous strip bounded between the two lines, which contains infinitely many coordinate pairs $(x, y)$.\nCorrect choice is B."
  },
  {
    id: "est1-sample1-q06",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Foundational Algebra",
    chapter: "Linear Equations & Systems",
    lesson: "Linear Inequalities & Shaded Coordinate Regions",
    difficulty: "medium",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 75,
    prompt: "Omar has $30 to spend on lunch for himself and his friends. He wants to buy sandwiches that cost $4.50 each and drinks that cost $1.50 each. If he buys 4 sandwiches, what is the maximum number of drinks he can buy?",
    question: "Omar has $30 to spend on lunch for himself and his friends. He wants to buy sandwiches that cost $4.50 each and drinks that cost $1.50 each. If he buys 4 sandwiches, what is the maximum number of drinks he can buy?",
    choices: [
      { id: "A", text: "6", isCorrect: false, is_correct: false, rationale: "Incorrect." },
      { id: "B", text: "7", isCorrect: false, is_correct: false, rationale: "Incorrect." },
      { id: "C", text: "8", isCorrect: true, is_correct: true, rationale: "Correct! 4 sandwiches cost $18. $30 - $18 = $12 remaining. $12 / 1.50 = 8 drinks." },
      { id: "D", text: "9", isCorrect: false, is_correct: false, rationale: "Incorrect. 9 drinks would cost $13.50 + $18 = $31.50, exceeding the $30 budget." }
    ],
    explanation: "Let $s$ be the number of sandwiches and $d$ be the number of drinks.\n$$4.50s + 1.50d \\le 30$$\nSubstitute $s = 4$:\n$$4.50(4) + 1.50d \\le 30$$\n$$18 + 1.50d \\le 30$$\n$$1.50d \\le 12$$\n$$d \\le \\frac{12}{1.50} = 8$$\nThus, the maximum number of drinks Omar can buy is 8.\nCorrect choice is C."
  },
  {
    id: "est1-sample1-q07",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Foundational Algebra",
    chapter: "Linear Equations & Systems",
    lesson: "Linear Inequalities & Shaded Coordinate Regions",
    difficulty: "medium",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 90,
    prompt: "Which of the following inequalities corresponds to the shaded region in the figure above?",
    question: "Which of the following inequalities corresponds to the shaded region in the figure above?",
    imageUrl: "/assets/est1-sample1/q07_inequality_graph.svg",
    imageCaption: "Coordinate plane with shaded region above the solid line",
    choices: [
      { id: "A", text: "-y \\le \\frac{1}{2}x - 3", isCorrect: false, is_correct: false, rationale: "Incorrect." },
      { id: "B", text: "-y \\le -\\frac{1}{2}x + 3", isCorrect: true, is_correct: true, rationale: "Correct! The line is $y = \\frac{1}{2}x - 3$. Shaded region above: $y \\ge \\frac{1}{2}x - 3 \\iff -y \\le -\\frac{1}{2}x + 3$." },
      { id: "C", text: "y \\le \\frac{1}{2}x - 3", isCorrect: false, is_correct: false, rationale: "Incorrect. Shading is above the line, not below." },
      { id: "D", text: "y \\ge -\\frac{1}{2}x + 3", isCorrect: false, is_correct: false, rationale: "Incorrect. The slope is positive 1/2, not negative." }
    ],
    explanation: "From the graph, the boundary line passes through $(0, -3)$ and $(6, 0)$ (or $(2, -2)$, $(4, -1)$).\nSlope $m = \\frac{0 - (-3)}{6 - 0} = \\frac{3}{6} = \\frac{1}{2}$.\n$y$-intercept is $(0, -3)$, so the boundary equation is:\n$$y = \\frac{1}{2}x - 3$$\nThe shaded region lies above this solid line:\n$$y \\ge \\frac{1}{2}x - 3$$\nMultiply both sides by $-1$ (which flips the inequality sign):\n$$-y \\le -\\left(\\frac{1}{2}x - 3\\right) = -\\frac{1}{2}x + 3$$\nTherefore, the correct choice is B."
  },
  {
    id: "est1-sample1-q08",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Advanced Algebra and Functions",
    chapter: "Quadratic & Polynomial Equations",
    lesson: "Factoring Techniques & Root Finding",
    difficulty: "easy",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 60,
    prompt: "If $f(x) = x^2 - 3x + 2$, what is the value of $f(-2)$?",
    question: "If $f(x) = x^2 - 3x + 2$, what is the value of $f(-2)$?",
    choices: [
      { id: "A", text: "12", isCorrect: true, is_correct: true, rationale: "Correct! $f(-2) = (-2)^2 - 3(-2) + 2 = 4 + 6 + 2 = 12$." },
      { id: "B", text: "8", isCorrect: false, is_correct: false, rationale: "Incorrect." },
      { id: "C", text: "4", isCorrect: false, is_correct: false, rationale: "Incorrect." },
      { id: "D", text: "0", isCorrect: false, is_correct: false, rationale: "Incorrect. 0 is $f(1)$ or $f(2)$." }
    ],
    explanation: "Substitute $x = -2$ into $f(x)$:\n$$f(-2) = (-2)^2 - 3(-2) + 2 = 4 + 6 + 2 = 12$$\nCorrect choice is A."
  },
  {
    id: "est1-sample1-q09",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Advanced Algebra and Functions",
    chapter: "Quadratic & Polynomial Equations",
    lesson: "Vertex Form & Parabola Optimization",
    difficulty: "medium",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 60,
    prompt: "What is the vertex of the parabola with equation $y = 2(x - 3)^2 + 5$?",
    question: "What is the vertex of the parabola with equation $y = 2(x - 3)^2 + 5$?",
    choices: [
      { id: "A", text: "(-3, 5)", isCorrect: false, is_correct: false, rationale: "Incorrect sign for h." },
      { id: "B", text: "(3, 5)", isCorrect: true, is_correct: true, rationale: "Correct! Vertex form is $y = a(x - h)^2 + k$ with vertex $(h, k) = (3, 5)$." },
      { id: "C", text: "(3, -5)", isCorrect: false, is_correct: false, rationale: "Incorrect sign for k." },
      { id: "D", text: "(-3, -5)", isCorrect: false, is_correct: false, rationale: "Incorrect signs for both h and k." }
    ],
    explanation: "The vertex form of a quadratic equation is:\n$$y = a(x - h)^2 + k$$\nwhere the vertex is the point $(h, k)$.\nComparing $y = 2(x - 3)^2 + 5$ with the standard form, we have $h = 3$ and $k = 5$.\nTherefore, the vertex is $(3, 5)$.\nCorrect choice is B."
  },
  {
    id: "est1-sample1-q10",
    exam: "EST I",
    targetExam: "EST I",
    collection: "EST I Math Sample Test #1",
    domain: "Algebra & Functions",
    category: "Advanced Algebra and Functions",
    chapter: "Rational & Radical Equations",
    lesson: "Extraneous Solutions in Radical Equations",
    difficulty: "medium",
    type: "MCQ",
    questionType: "multiple_choice",
    calculatorAllowed: true,
    estimatedSeconds: 80,
    prompt: "What is the solution set of the equation $\\sqrt{2x + 3} = x$?",
    question: "What is the solution set of the equation $\\sqrt{2x + 3} = x$?",
    choices: [
      { id: "A", text: "{-1, 3}", isCorrect: false, is_correct: false, rationale: "Incorrect. $x = -1$ is an extraneous root because $\\sqrt{1} \\ne -1$." },
      { id: "B", text: "{3}", isCorrect: true, is_correct: true, rationale: "Correct! Squaring yields $x^2 - 2x - 3 = 0$. Checking roots gives only $x = 3$ valid." },
      { id: "C", text: "{-1}", isCorrect: false, is_correct: false, rationale: "Incorrect. -1 is extraneous." },
      { id: "D", text: "\\emptyset", isCorrect: false, is_correct: false, rationale: "Incorrect. 3 is a valid solution." }
    ],
    explanation: "Given $\\sqrt{2x + 3} = x$. Note that $x \\ge 0$ must hold since the principal square root is non-negative.\nSquare both sides:\n$$2x + 3 = x^2$$\n$$x^2 - 2x - 3 = 0$$\nFactor:\n$$(x - 3)(x + 1) = 0 \\implies x = 3 \\text{ or } x = -1$$\nCheck solutions:\n- For $x = 3$: $\\sqrt{2(3) + 3} = \\sqrt{9} = 3$ (True)\n- For $x = -1$: $\\sqrt{2(-1) + 3} = \\sqrt{1} = 1 \\ne -1$ (Extraneous)\nThus the solution set is $\{3\}$.\nCorrect choice is B."
  }
];

console.log(`Loaded initial ${questions.length} sample items.`);
